module.exports = {
    ...require('./__proto__.js'),
    data: {
        marketData: [
            {
                name: 'Farmers Market',
                address1: 'Address Line 1',
                address2: 'Address Line 2',
                date: 'Dates',
                time: 'Times',
            },
            {
                name: 'Farmers Market',
                address1: 'Address Line 1',
                address2: 'Address Line 2',
                date: 'Dates',
                time: 'Times',
            },
            {
                name: 'Farmers Market',
                address1: 'Address Line 1',
                address2: 'Address Line 2',
                date: 'Dates',
                time: 'Times',
            },
            {
                name: 'Farmers Market',
                address1: 'Address Line 1',
                address2: 'Address Line 2',
                date: 'Dates',
                time: 'Times',
            },
            {
                name: 'Farmers Market',
                address1: 'Address Line 1',
                address2: 'Address Line 2',
                date: 'Dates',
                time: 'Times',
            },
            {
                name: 'Farmers Market',
                address1: 'Address Line 1',
                address2: 'Address Line 2',
                date: 'Dates',
                time: 'Times',
            },
        ],
        imageData: [
            {
                className: 'arrow',
                filename: 'LeftArrow.png',
                alt: 'Left Arrow',
                date: '',
                caption: '',
            },
            {
                className: 'calendar-image',
                filename: 'Jam.jpg',
                alt: 'Jam',
                date: 'Nov. 12',
                caption: 'Wild Berry Jam',
            },
            {
                className: 'calendar-image',
                filename: 'Beets.jpg',
                alt: 'Beets',
                date: 'Oct. 4',
                caption: 'We Got The Beets',
            },
            {
                className: 'calendar-image',
                filename: 'Squash.jpg',
                alt: 'Squash',
                date: 'Oct. 13',
                caption: "It's Time For Squash",
            },
            {
                className: 'arrow',
                filename: 'RightArrow.png',
                alt: 'Right Arrow',
                date: '',
                caption: '',
            },
        ],
    },
}
